services:
  db:
    #dockerfileを使わずにイメージを指定する場合
    image: postgres:latest
    environment:
      POSTGRES_USER: sample_user
      POSTGRES_DB: sample_DB
      POSTGRES_PASSWORD: sample_password
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: pg_isready -U sample_user -d sample_DB
      interval: 2s
      timeout: 3s
      retries: 40

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"  # 手動migrate必要
    # entrypoint: ./wait-for-it.sh db:5432    ←1分後くらいに自動migrate
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development # 開発環境であることを明示
      DATABASE_URL: postgres://sample_user:sample_password@db:5432/sample_DB # DBの接続情報も環境変数で指定
      SECRET_KEY_BASE: development_key # 開発用のシークレットキー

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" #react
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  express:  # Express API
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    ports:
      - "8080:8080"  

